name: Commit tagger
  # You may pin to the exact commit or the version.
  # uses: tvdias/github-tagger@ed7350546e3e503b5e942dffd65bc8751a95e49d
  uses: tvdias/github-tagger@v0.0.2
  with:
    # The GITHUB_TOKEN secret
    repo-token: # optional
    # Tag text
    tag: 1 # optional, default is 0.1.0
    # optional commit sha to apply the tag to
    commit-sha: # optional
